name: release

on:
  push:
    tags: ["v*.*.*"]

permissions:
  actions: read
  contents: write

jobs:
  release:
    name: Create GitHub Release
    runs-on: ubuntu-22.04

    steps:
      - name: Download build artifacts from previous workflow
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: build.yml
          workflow_conclusion: success
          branch: master
          skip_unpack: true
          path: release

      - name: Create release
        uses: softprops/action-gh-release@v3
        with:
          files: release/**
        env:
          GITHUB_TOKEN: ${{ secrets.token }}
